### ISSUE TITLE
Use control flow primitives from operatorkit to prevent error alerts

### ISSUE THREAD

**Issue by fgimenez** [giantswarm/cluster-operator#103]
In general we should cancel reconciliation on expected/recurring errors instead of letting them bubble up.

**Comment by xh3b4sd** [comment]
> Right now we rely on the retry resource to cover unexpected issues to just retry in general. In case we want to retry on purpose because we expect the stuff to not be ready, just like the tiller setup, we should not do this via dispatching errors down the stack. So now we still get the error rate alerts with this approach. I suggest we should work with the control flow primitives we have in operatorkit instead. We can for instance cancel resource reconciliation once we see a certain error which we expect to persist for a couple of seconds or minutes and try to catch up on the next resync period.

See https://gigantic.slack.com/archives/C2MS2VB37/p1525877195000420.

**Comment by fgimenez** [comment]
Done in #107
